# This workflow will build a Xcode project

name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, macOS, ARM64]

    steps:
    - uses: actions/checkout@v3
    - name: Build x86_64
      run: xcodebuild -arch x86_64
    - name: Move x86_64
      run: mkdir tmp && mv macOSHelper.app tmp/
    - name: Upload -x86_64
      uses: actions/upload-artifact@v3
      with:
        name: macOSHelper-x86_64
        path: build/Release/tmp
    - name: Delete temp folder
      run: rm -rf tmp
    - name: Build arm64
      run: xcodebuild -arch arm64
    - name: Move arm64
      run: mkdir tmp && mv macOSHelper.app tmp/
    - name: Upload -arm64
      uses: actions/upload-artifact@v3
      with:
        name: macOSHelper-arm64
        path: build/Release/tmp
    - name: Delete temp folder
      run: rm -rf tmp
