# This workflow will build a Xcode project

name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build x86_64
      run: xcodebuild -arch x86_64
    - name: Build arm64
      run: xcodebuild -arch arm64
